spring.application.name=lista-tarefas-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/lista_tarefas
spring.datasource.username=postgres
spring.datasource.password=Gabi0510

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=false

server.port=8080
